/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import org.icepdf.ri.common.SwingController;

/**
 *
 * @author Mariam Eltorky
 */
public class NormalUserGUI extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form NormalUserGUI
     */
    public NormalUserGUI() {
        initComponents();
     this.setLocationRelativeTo(null);
        addWindowListener(this);
        setIcon();
     
    }

    public void setContracttype(JComboBox<String> contracttype) {
        this.contracttype = contracttype;
    }

    public void setKindoforganization(JComboBox<String> kindoforganization) {
        this.kindoforganization = kindoforganization;
    }

    public void setProjectlocation(JComboBox<String> projectlocation) {
        this.projectlocation = projectlocation;
    }

    public void setProjectsize(JComboBox<String> projectsize) {
        this.projectsize = projectsize;
    }

    public void setProjecttype(JComboBox<String> projecttype) {
        this.projecttype = projecttype;
    }

    public void setShowrecommendation(JButton showrecommendation) {
        this.showrecommendation = showrecommendation;
    }

    public JComboBox<String> getContracttype() {
        return contracttype;
    }

    public JComboBox<String> getKindoforganization() {
        return kindoforganization;
    }

    public JComboBox<String> getProjectlocation() {
        return projectlocation;
    }

    public JComboBox<String> getProjectsize() {
        return projectsize;
    }

    public JComboBox<String> getProjecttype() {
        return projecttype;
    }

    public JButton getShowrecommendation() {
        return showrecommendation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        projectlocation = new javax.swing.JComboBox<>();
        projecttype = new javax.swing.JComboBox<>();
        projectsize = new javax.swing.JComboBox<>();
        kindoforganization = new javax.swing.JComboBox<>();
        contracttype = new javax.swing.JComboBox<>();
        showrecommendation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Project Location");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 290, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Project Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 230, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Project Size");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 210, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contract Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Organization ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kind of ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 150, 40));

        jLabel8.setFont(new java.awt.Font("Constantia", 3, 50)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(160, 185, 189));
        jLabel8.setText("Risk Identification");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 460, 90));

        projectlocation.setBackground(new java.awt.Color(204, 204, 204));
        projectlocation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        projectlocation.setForeground(new java.awt.Color(26, 49, 83));
        projectlocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Remote Location", "Non-Remote Location" }));
        projectlocation.setSelectedIndex(-1);
        projectlocation.setSelectedItem(null);
        projectlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectlocationActionPerformed(evt);
            }
        });
        getContentPane().add(projectlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 310, 60));

        projecttype.setBackground(new java.awt.Color(204, 204, 204));
        projecttype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        projecttype.setForeground(new java.awt.Color(26, 49, 83));
        projecttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infrastructure/Tunnels", "Buildings Construction" }));
        projecttype.setSelectedIndex(-1);
        projecttype.setSelectedItem(null);
        projecttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projecttypeActionPerformed(evt);
            }
        });
        getContentPane().add(projecttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 310, 60));

        projectsize.setBackground(new java.awt.Color(204, 204, 204));
        projectsize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        projectsize.setForeground(new java.awt.Color(26, 49, 83));
        projectsize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mega", "Medium" }));
        projectsize.setSelectedIndex(-1);
        projectsize.setSelectedItem(null);
        projectsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsizeActionPerformed(evt);
            }
        });
        getContentPane().add(projectsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 310, 60));

        kindoforganization.setBackground(new java.awt.Color(204, 204, 204));
        kindoforganization.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kindoforganization.setForeground(new java.awt.Color(26, 49, 83));
        kindoforganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client/Consultant", "Contractor" }));
        kindoforganization.setSelectedIndex(-1);
        kindoforganization.setSelectedItem(null);
        kindoforganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kindoforganizationActionPerformed(evt);
            }
        });
        getContentPane().add(kindoforganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 310, 60));

        contracttype.setBackground(new java.awt.Color(204, 204, 204));
        contracttype.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        contracttype.setForeground(new java.awt.Color(26, 49, 83));
        contracttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EPC", "Design and Built" }));
        contracttype.setSelectedIndex(-1);
        contracttype.setSelectedItem(null);
        contracttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contracttypeActionPerformed(evt);
            }
        });
        getContentPane().add(contracttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 310, 60));

        showrecommendation.setBackground(new java.awt.Color(204, 204, 255));
        showrecommendation.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        showrecommendation.setForeground(new java.awt.Color(26, 49, 83));
        showrecommendation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmanagement/nextb.png"))); // NOI18N
        showrecommendation.setPreferredSize(new java.awt.Dimension(69, 40));
        showrecommendation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showrecommendationActionPerformed(evt);
            }
        });
        getContentPane().add(showrecommendation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 150, 70));

        jLabel1.setFont(new java.awt.Font("Constantia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmanagement/NormalUserBackGround.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectlocationActionPerformed

    private void projecttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projecttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projecttypeActionPerformed

    private void projectsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectsizeActionPerformed

    private void kindoforganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kindoforganizationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kindoforganizationActionPerformed

    private void contracttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contracttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contracttypeActionPerformed

    private void showrecommendationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showrecommendationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showrecommendationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NormalUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NormalUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NormalUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NormalUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NormalUserGUI().setVisible(true);
                 
            }
             
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> contracttype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> kindoforganization;
    private javax.swing.JComboBox<String> projectlocation;
    private javax.swing.JComboBox<String> projectsize;
    private javax.swing.JComboBox<String> projecttype;
    private javax.swing.JButton showrecommendation;
    // End of variables declaration//GEN-END:variables
public void addController(ActionListener cont) {
    showrecommendation.addActionListener(cont);
       
}
public void setIcon () {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    @Override
    public void windowOpened(WindowEvent we) {
     //   throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public  void windowClosing(WindowEvent we) {
         
        try {
            String fileNameD="D:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameD));
            String fileNameE="E:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameE));
            String fileNameF="F:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameF));
            String fileNameG="G:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameG));
            String fileNameH="H:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameH));
            System.out.println("Deleted From Normal User ING");
        } catch (IOException ex) {
            Logger.getLogger(NormalUserGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void windowClosed(WindowEvent we) {
         System.out.println("Deleted From Normal User ED");
         File file=new File("D:\\Recommendation.pdf");
         if (file.exists()) {
         file.delete();
         }
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent we) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent we) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent we) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent we) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
