/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagement;

import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Mariam Eltorky
 */
public class SuperUserGUI extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form SuperUserGUI
     */
    public SuperUserGUI() {
        initComponents();
        addWindowListener(this);
    }

    public void setAction(JTextField action) {
        this.action = action;
    }

    public void setAdd(JButton add) {
        this.add = add;
    }

    public void setDelet(JButton delet) {
        this.delet = delet;
    }

    public void setFactor(JTextField factor) {
        this.factor = factor;
    }

    public void setGroup(JTextField group) {
        this.group = group;
    }

    public void setId(JTextField id) {
        this.id = id;
    }

    public void setShow(JButton show) {
        this.show = show;
    }

    public void setStra(JTextField stra) {
        this.stra = stra;
    }

    public JTextField getAction() {
        return action;
    }

    public JButton getAdd() {
        return add;
    }

    public JButton getDelet() {
        return delet;
    }

    public JTextField getFactor() {
        return factor;
    }

    public JTextField getGroup() {
        return group;
    }

    public JTextField getId() {
        return id;
    }

    public JButton getShow() {
        return show;
    }

    public JTextField getStra() {
        return stra;
    }

    public JTable getTable() {
        return table;
    }

    public JButton getLogoutsuper() {
        return logoutsuper;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        group = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        factor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        stra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        action = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        delet = new javax.swing.JButton();
        show = new javax.swing.JButton();
        logoutsuper = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 40, 40));

        id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 90, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Group");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 80, 40));

        group.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupActionPerformed(evt);
            }
        });
        getContentPane().add(group, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 110, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Recommended Risk Factors");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        factor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorActionPerformed(evt);
            }
        });
        getContentPane().add(factor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 440, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Recommended Response Strategy");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 430, -1));

        stra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                straActionPerformed(evt);
            }
        });
        getContentPane().add(stra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 440, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recommended Response Action");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        action.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionActionPerformed(evt);
            }
        });
        getContentPane().add(action, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 440, 50));

        add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add.setForeground(new java.awt.Color(26, 49, 83));
        add.setText("ADD");
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 150, 50));

        delet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        delet.setForeground(new java.awt.Color(26, 49, 83));
        delet.setText("Delete");
        getContentPane().add(delet, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, 150, 50));

        show.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        show.setForeground(new java.awt.Color(26, 49, 83));
        show.setText("Show");
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 260, 150, 50));

        logoutsuper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmanagement/logout.png"))); // NOI18N
        getContentPane().add(logoutsuper, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 100, 90));

        table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Recommended Risk Factors", "Recommended Response Strategy", "Recommended Response Action", "Group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1290, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectmanagement/SuperUserBackGround.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1420, 870));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupActionPerformed

    private void factorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factorActionPerformed

    private void straActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_straActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_straActionPerformed

    private void actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField action;
    private javax.swing.JButton add;
    private javax.swing.JButton delet;
    private javax.swing.JTextField factor;
    private javax.swing.JTextField group;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutsuper;
    private javax.swing.JButton show;
    private javax.swing.JTextField stra;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables


public void addController(ActionListener cont) {
    add.addActionListener(cont);
    delet.addActionListener(cont);
    show.addActionListener(cont);
    logoutsuper.addActionListener(cont);
}

    @Override
    public void windowOpened(WindowEvent we) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent we) {
        try {
          
           String fileNameD="D:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameD));
            String fileNameE="E:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameE));
            String fileNameF="F:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameF));
            String fileNameG="G:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameG));
            String fileNameH="H:\\Recommendation.pdf";
            Files.deleteIfExists(Paths.get(fileNameH));
            System.out.println("Deleted From Super User ING");
        } catch (IOException ex) {
            Logger.getLogger(NormalUserGUI.class.getName()).log(Level.SEVERE, null, ex);
        }}

    @Override
    public void windowClosed(WindowEvent we) {
         System.out.println("Deleted From Super User ED");
         File file=new File("D:\\Recommendation.pdf");
         if (file.exists()) {
         file.delete();
         }
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent we) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent we) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent we) {
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent we) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
